# Generated by Django 5.2.4 on 2025-07-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True, verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
    ]
