# Generated by Django 5.2.4 on 2025-07-21 02:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_genre_remove_movie_directors_remove_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название фильма'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(models.OrderBy(django.db.models.functions.text.Lower('name'), descending=True), name='unique_genre_name_case_insensitive'),
        ),
    ]
